eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: 9096

spring:
  application:
    name: "api-gateway"
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8992/
          predicates:
            - Path=/api/v1/**
        - id: job-seeker-service
          uri: http://localhost:9091/
          predicates:
            - Path=/jobseeker/**
        - id: recruiter-service
          uri: http://recruiter-service:8090/
          predicates:
            - Path=/fitmyjob/**

        - id: jobsearch service
          uri: http://localhost:8888/
          predicates:
            - Path=/jobs/**

        - id: webservice
          uri: http://localhost:8888/
          predicates:
            - Path=/fitmyjob/**

        - id: feedback service
          uri: http://localhost:9095/
          predicates:
            - Path=/fitmyjob/**

        - id: email service
          uri: http://localhost:8070/
          predicates:
            - Path=/api/v1/**
        - id: chat service
          uri: http://localhost:9096/
          predicates:
            - Path=/api/v1/**
