eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: 9096

spring:
  application:
    name: "api-gateway"
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:1992/
          predicates:
            - Path=/api-docs
        - id: job-seeker-service
          uri: http://localhost:9091/
          predicates:
            - Path=/jobseeker/**
        - id: recruiter-service
          uri: http://recruiter-service:8099/
          predicates:
            - Path=/fitmyjob/**

        - id: job-search-service
          uri: http://localhost:8888/
          predicates:
            - Path=/jobs/**

        - id: Job-Service
          uri: http://localhost:9090/
          predicates:
            - Path=/jobpost/**

        - id: feedback service
          uri: http://localhost:9095/
          predicates:
            - Path=/feedback/**

        - id: email-Service
          uri: http://localhost:8070/
          predicates:
            - Path=/email/**
        - id: chat-service
          uri: http://localhost:8090/
          predicates:
            - Path=/v1/api/**
